dist: trusty
addons:
  chrome: stable
language: ruby
sudo: false

notifications:
  email: false

matrix:
  include:
    - rvm: 2.5.0
      env: "RAILS_VERSION=5.1.5"
    - rvm: 2.4.3
      env: "RAILS_VERSION=5.2.0.rc2"
    - rvm: 2.4.3
      env: "RAILS_VERSION=5.1.5"
    - rvm: 2.3.4
      env: "RAILS_VERSION=5.0.6"
    - rvm: jruby-9.1.16.0
      env: "RAILS_VERSION=5.1.5 JRUBY_OPTS=\"-J-Xms512m -J-Xmx1024m\""
  allow_failures:
    - rvm: jruby-9.1.16.0
  fast_finish: true

before_install:
  - gem update --system
  - gem install bundler
  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &

notifications:
  irc: "irc.freenode.org#blacklight"
  email:
      - blacklight-commits@googlegroups.com

global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - ENGINE_CART_RAILS_OPTIONS='--skip-git --skip-bundle --skip-listen --skip-spring --skip-yarn --skip-keeps --skip-action-cable --skip-coffee --skip-test'

jdk: oraclejdk8
