language: ruby
sudo: false
cache:
  directories:
  - /tmp/solr-5.2.1

notifications:
  email: false

rvm:
  - 2.2.2

matrix:
  include:
    - rvm: 2.2.2
      env: "RAILS_VERSION=4.1.9"
    - rvm: 2.1.6
      env: "RAILS_VERSION=4.2.1"
  allow_failures:
    - rvm: jruby
      env: "RAILS_VERSION=4.2.1 JRUBY_OPTS=\"-J-Xms512m -J-Xmx1024m\""

before_install:
  - gem install bundler

env:
 - "RAILS_VERSION=4.2.1"

notifications:
  irc: "irc.freenode.org#blacklight"
  email:
      - blacklight-commits@googlegroups.com

global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
