language: ruby
sudo: false
cache:
  directories:
  - /tmp/solr-5.3.0

notifications:
  email: false

rvm:
  - 2.3.0

matrix:
  include:
    - rvm: 2.2.4
      env: "RAILS_VERSION=4.1.14"
    - rvm: 2.1.6
      env: "RAILS_VERSION=4.2.5"
    - rvm: 2.2.4
      env: "RAILS_VERSION=4.2.5"
    - rvm: 2.2.4
      env: "RAILS_VERSION=edge"
    - rvm: jruby-9.0.4.0
      env: "RAILS_VERSION=4.2.5 JRUBY_OPTS=\"-J-Xms512m -J-Xmx1024m\""
  allow_failures:
    - rvm: jruby-9.0.4.0
  fast_finish: true

before_install:
  - gem install bundler

env:
 - "RAILS_VERSION=4.2.5"

notifications:
  irc: "irc.freenode.org#blacklight"
  email:
      - blacklight-commits@googlegroups.com

global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
