sudo: false
language: ruby
rvm:
  - 2.3.7

matrix:
  include:
    - rvm: 2.3.7
      env: "RAILS_VERSION=4.0.13"
    - rvm: 2.3.7
      env: "RAILS_VERSION=4.1.16"
    - rvm: 2.3.7
      env: "RAILS_VERSION=4.2.10"

notifications:
  irc: "irc.freenode.org#blacklight"
  email: false

env: JRUBY_OPTS="-J-Xms512m -J-Xmx1024m"
