dist: bionic
addons:
  chrome: stable
language: ruby

notifications:
  email: false

matrix:
  include:
    - rvm: 2.6.4
      env: "RAILS_VERSION=5.2.2"
    - rvm: 2.6.4
      env: "RAILS_VERSION=6.0.0"
    - rvm: 2.5.3
      env: "RAILS_VERSION=5.1.6"
    - rvm: 2.5.3
      env: "RAILS_VERSION=5.2.1 BLACKLIGHT_API_TEST=true ENGINE_CART_RAILS_OPTIONS=\"--api --skip-git --skip-bundle --skip-listen --skip-spring --skip-yarn --skip-keeps --skip-action-cable  --skip-action-text --skip-action-mailbox --skip-coffee --skip-test --skip-javascript\""
    - rvm: 2.4.5
      env: "RAILS_VERSION=5.1.6"
    - rvm: jruby-9.2.0.0
      env: "RAILS_VERSION=5.1.6 JRUBY_OPTS=\"-J-Xms512m -J-Xmx1024m\""
  allow_failures:
    - rvm: jruby-9.2.0.0
  fast_finish: true

before_install:
  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &

notifications:
  irc: "irc.freenode.org#blacklight"
  email:
      - blacklight-commits@googlegroups.com

global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - ENGINE_CART_RAILS_OPTIONS='--skip-git --skip-bundle --skip-listen --skip-spring --skip-bootsnap --skip-yarn --skip-keeps --skip-action-cable --skip-active-storage --skip-action-text --skip-action-mailbox --skip-coffee --skip-test'
  - CC_TEST_REPORTER_ID=5042c7358c96b0b926088a4cda3e132fffe7a66ce8047cdb1dc6f0b4b6676b79

jdk: openjdk11

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
