notifications:
  email: false

rvm:
  - 1.9.3
  - jruby-19mode
  - 2.0.0

gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails4.gemfile

notifications:
  irc: "irc.freenode.org#blacklight"
  email:
      - blacklight-commits@googlegroups.com

env:
  global:
    - JRUBY_OPTS="-J-Xms512m -J-Xmx1024m"
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - CURRENT_ENGINE_NAME=blacklight-bootstrap3
