language: ruby
sudo: false

notifications:
  email: false

rvm:
  - 2.4.1

matrix:
  include:
    - rvm: 2.4.1
      env: "RAILS_VERSION=4.2.8"
    - rvm: 2.2.7
      env: "RAILS_VERSION=5.0.3"
    - rvm: 2.3.4
      env: "RAILS_VERSION=5.1.1"
    - rvm: jruby-9.1.7.0
      env: "RAILS_VERSION=5.0.3 JRUBY_OPTS=\"-J-Xms512m -J-Xmx1024m\""
  allow_failures:
    - rvm: jruby-9.1.7.0
  fast_finish: true

before_install:
  - gem update --system
  - gem install bundler

before_script:
  - if [[ "${RAILS_VERSION}" =~ ^4.2.* ]]; then perl -pi -e "s/ActiveRecord::Migration\[[\d\.]+\]/ActiveRecord::Migration/" db/migrate/*; fi

env:
 - "RAILS_VERSION=5.1.1"

notifications:
  irc: "irc.freenode.org#blacklight"
  email:
      - blacklight-commits@googlegroups.com

global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

jdk: oraclejdk8
