language: ruby
sudo: false

notifications:
  email: false

rvm:
  - 2.4.1

matrix:
  include:
    - rvm: 2.3.4
      env: "RAILS_VERSION=5.0.5"
    - rvm: jruby-9.1.12.0
      env: "RAILS_VERSION=5.1.3 JRUBY_OPTS=\"-J-Xms512m -J-Xmx1024m\""
  allow_failures:
    - rvm: jruby-9.1.12.0
  fast_finish: true

before_install:
  - gem update --system
  - gem install bundler

env:
 - "RAILS_VERSION=5.1.3"

notifications:
  irc: "irc.freenode.org#blacklight"
  email:
      - blacklight-commits@googlegroups.com

global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

jdk: oraclejdk8
