# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: release-8.x scheduled

on:
  schedule:
    # Weekly at 9:35 on Friday
    # Somewhat weird timing so that it isn't delayed too much
    - cron: '35 9 * * 5'
jobs:
  lint:
    uses: maxkadel/actions/.github/workflows/lint.yml@main
    with:
      ref: release-8.x
  test:
    uses: maxkadel/actions/.github/workflows/test.yml@main
    with:
      ref: release-8.x
      ruby: '["3.3"]'
  docker_build:
    uses: maxkadel/actions/.github/workflows/build.yml@main
    with:
      ref: release-8.x
  report:
    runs-on: ubuntu-latest
    if: ${{ always() && contains(join(needs.*.result, ','), 'failure') }}
    needs: [lint, test, docker_build]
    steps:
      - name: Report on failure of any dependent job
        env:
          NEEDS: ${{ toJSON(needs) }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "The weekly CI run of the release-8.x branch has failed"
