# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: CI

on:
  push:
    branches:
      - main
      - 'release-*'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler: 'default'
    - name: Install dependencies
      run: bundle install
    - name: Run linter
      run: bundle exec rake rubocop
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [3.1, 3.2]
    env:
      RAILS_VERSION: 7.0.8
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: 'default'
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake ci
      env:
        ENGINE_CART_RAILS_OPTIONS: '--skip-git --skip-listen --skip-spring --skip-keeps --skip-coffee --skip-test'
  test_bootstrap5:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.0']
    env:
      RAILS_VERSION: 7.0.8
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: 'default'
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake ci
      env:
        BOOTSTRAP_VERSION: '~> 5.0'
        ENGINE_CART_RAILS_OPTIONS: '--skip-git --skip-listen --skip-spring --skip-keeps --skip-coffee --skip-test'
  test_rails6_0:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.6]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: 'default'
    - name: Install dependencies
      run: bundle install
      env:
        RAILS_VERSION: 6.0.5.1
    - name: Run tests
      run: bundle exec rake ci
      env:
        RAILS_VERSION: 6.0.5.1
        ENGINE_CART_RAILS_OPTIONS: '--skip-git --skip-listen --skip-spring --skip-keeps --skip-action-cable --skip-coffee --skip-test'
  test_rails5_2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: 'default'
    - name: Install dependencies
      run: bundle install
      env:
        RAILS_VERSION: 5.2.8.1
    - name: Run tests
      run: bundle exec rake ci
      env:
        RAILS_VERSION: 5.2.8.1
        ENGINE_CART_RAILS_OPTIONS: '--skip-git --skip-listen --skip-spring --skip-keeps --skip-action-cable --skip-coffee --skip-test'
  test_rails6_1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.0']
    env:
      RAILS_VERSION: 6.1.6.1
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: 'default'
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake ci
      env:
        ENGINE_CART_RAILS_OPTIONS: '--skip-git --skip-keeps --skip-action-cable --skip-test'
  test_vc3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.2']
    env:
      RAILS_VERSION: 7.0.8
      VIEW_COMPONENT_VERSION: ${{ matrix.view_component_version }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: 'default'
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake ci
      env:
        ENGINE_CART_RAILS_OPTIONS: '--skip-git --skip-listen --skip-spring --skip-keeps --skip-coffee --skip-test'
  api_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.7, '3.0']
    env:
      RAILS_VERSION: 7.0.8
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler: 'default'
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake ci
      env:
        BLACKLIGHT_API_TEST: true
        ENGINE_CART_RAILS_OPTIONS: '-a propshaft --api --skip-git --skip-bundle --skip-listen --skip-spring --skip-yarn --skip-keeps --skip-action-cable --skip-coffee --skip-test'
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        run: docker compose build app
